project:
  type: website
  output-dir: docs        # GitHub Pages will serve from /docs
  resources: images/**

website:
  title: "Climate Gazette"
  navbar:
      search: false
      logo: images/logo-gazette.svg
      logo-alt: "Climate Gazette"
      logo-href: "index.qmd"
      title: false
      




format:
  html:
    page-layout: full
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    echo: false  




